"""Utilities for handling pre-split datasets used in ToxCast_model_v.3.

This module centralises the logic required to load the ``train``/``val``/``test``
CSV files and their associated fingerprint matrices.  Version 3 of the
ToxCast pipeline expects each split directory to contain a ``*_df.csv`` file
and a ``fingerprints`` sub-directory that mirrors the layout described in the
user instructions.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import pandas as pd


DEFAULT_NON_ASSAY_COLUMNS = ("DTXSID", "SMILES")


def _normalise_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Normalise obvious helper columns such as ``SMILES`` and ``DTXSID``.

    The CSV files can originate from multiple sources which might use slightly
    different capitalisation or add whitespace.  Normalising upfront makes the
    downstream logic robust without imposing strict requirements on the input
    files.
    """

    def _canonical(name: str) -> str:
        return name.strip().replace("\u200b", "").replace("\ufeff", "")

    renamed = {col: _canonical(str(col)) for col in df.columns}
    df = df.rename(columns=renamed)

    lower = {str(col).lower(): col for col in df.columns}
    for key in ("smiles", "canonical smiles", "cano_smiles", "mol_smiles"):
        if key in lower:
            df = df.rename(columns={lower[key]: "SMILES"})
            break
    for key in ("dtxsid", "dtxs_id", "dtxsid (dtxcid)"):
        if key in lower:
            df = df.rename(columns={lower[key]: "DTXSID"})
            break
    return df


def load_split_dataframe(csv_path: Path) -> pd.DataFrame:
    """Read a CSV file and drop autogenerated ``Unnamed`` columns.

    Parameters
    ----------
    csv_path:
        Path to ``*_df.csv``.
    """

    df = pd.read_csv(csv_path)
    drop_cols = [c for c in df.columns if str(c).startswith("Unnamed")]
    if drop_cols:
        df = df.drop(columns=drop_cols)
    return _normalise_columns(df)


def read_drop_indices(drop_path: Path) -> list[int]:
    """Return the drop indices stored in ``*_dropidx.csv`` if it exists."""

    if not drop_path.exists() or drop_path.stat().st_size == 0:
        return []

    try:
        df = pd.read_csv(drop_path)
    except pd.errors.EmptyDataError:
        return []

    # Some files save the column using the fingerprint name, others simply use
    # ``index`` or no header at all.  Normalise these variations.
    if df.empty:
        return []

    if df.shape[1] == 1:
        return df.iloc[:, 0].dropna().astype(int).tolist()

    # Fall back to collecting every column to guard against formatting quirks.
    drop_values: list[int] = []
    for col in df.columns:
        drop_values.extend(df[col].dropna().astype(int).tolist())
    return drop_values


@dataclass
class SplitData:
    features: pd.DataFrame
    labels: pd.Series | None
    smiles: pd.Series | None

    def dropna(self) -> "SplitData":
        """Return a copy with NaN labels removed.

        Some datasets omit the label column (e.g. prediction inputs).  In that
        case the instance is returned unchanged.
        """

        if self.labels is None:
            return self
        mask = self.labels.notna()
        features = self.features.loc[mask].reset_index(drop=True)
        labels = self.labels.loc[mask].reset_index(drop=True)
        smiles = (
            self.smiles.loc[mask].reset_index(drop=True)
            if self.smiles is not None
            else None
        )
        return SplitData(features=features, labels=labels, smiles=smiles)


def load_split_data(
    split_dir: Path,
    fingerprint_type: str,
    assay_name: str | None,
) -> SplitData:
    """Load the features/labels for a given split directory.

    Parameters
    ----------
    split_dir:
        Directory containing ``*_df.csv`` and the ``fingerprints`` folder.
    fingerprint_type:
        One of ``MACCS``, ``Morgan`` ... matching the CSV files in
        ``fingerprints``.
    assay_name:
        Name of the target column.  If ``None`` the labels field will be
        returned as ``None`` (useful for pure prediction inputs).
    """

    split_dir = Path(split_dir)
    df_path = split_dir / f"{split_dir.name}_df.csv"
    if not df_path.exists():
        raise FileNotFoundError(f"{df_path} does not exist")

    df = load_split_dataframe(df_path)

    fingerprint_dir = split_dir / "fingerprints"
    fp_path = fingerprint_dir / f"{fingerprint_type}.csv"
    if not fp_path.exists():
        raise FileNotFoundError(f"Fingerprint file missing: {fp_path}")

    features = pd.read_csv(fp_path)
    drop_idx = read_drop_indices(fingerprint_dir / f"{fingerprint_type}_dropidx.csv")
    if drop_idx:
        features = features.drop(index=drop_idx).reset_index(drop=True)
        df = df.drop(index=drop_idx).reset_index(drop=True)

    smiles = df.get("SMILES")
    labels = df.get(assay_name) if assay_name is not None else None

    split = SplitData(features=features, labels=labels, smiles=smiles)
    return split.dropna()


def get_assay_names_from_csv(
    csv_path: Path,
    skip_columns: Iterable[str] | None = None,
) -> list[str]:
    """Return assay column names inferred from ``train_df.csv``.

    The heuristic skips the obvious metadata columns (``DTXSID`` and
    ``SMILES``) and returns the remaining column names.
    """

    df = load_split_dataframe(Path(csv_path))

    skip_cols = set(DEFAULT_NON_ASSAY_COLUMNS)
    if skip_columns:
        skip_cols.update(skip_columns)

    assay_names = [col for col in df.columns if col not in skip_cols]
    if not assay_names:
        raise ValueError(
            f"No assay columns detected in {csv_path}. Columns={list(df.columns)}"
        )
    return assay_names


def ensure_matching_indices(*datasets: SplitData) -> None:
    """Validate that all datasets share the same row count.

    The function raises a ``ValueError`` when the feature matrices do not align,
    providing an early signal that the supplied inputs are inconsistent.
    """

    lengths = {data.features.shape[0] for data in datasets if data is not None}
    if len(lengths) > 1:
        raise ValueError(
            "Fingerprint matrices and CSV files must align. Found row counts: "
            + ", ".join(map(str, sorted(lengths)))
        )

